<template>
   <div>
      <div class="generator">
         <img src="/image-1.png" alt="bg-img" class="generator__bg" />
         <div class="generator__body">
            <div class="generator__header" v-if="lang_type == 'usa' || ''">
               YOU CAN SHARE THE TWEET DIRECTLY BY CLICKING THE TWEET BUTTON.
               YOU DO NOT NEED TO ADD ANY TEXT.
            </div>
            <div class="generator__header" v-else>
               Tweetle BUTONUNA BASARAK DOĞRUDAN TWEETİ PAYLAŞABİLİRSİNİZ.
               HERHANGİ BİR METİN EKLEMENİZE GEREK YOKTUR.
            </div>
            <div class="generator__text">
               {{ random_text }}
               <v-divider class="my-6"></v-divider>
               <v-btn
                  rounded
                  color="primary"
                  href="https://twitter.com/share?ref_src=twsrc%5Etfw"
                  class="text-capitalize tweet twitter-share-button mt-n4"
                  data-show-count="false"
                  data-size="large"
                  :data-text="random_text"
                  target="_blank"
                  data-url="#hamsterarmy"
                  small
               >
                  <v-icon class="mr-1">mdi-twitter</v-icon>
                  Tweet
               </v-btn>
               <v-btn
                  rounded
                  color="success"
                  class="text-capitalize refresh mt-n4 ml-3"
                  @click="refresh"
                  small
               >
                  {{ lang_type == "usa" || "" ? "Refresh" : "Yenile" }}
               </v-btn>
            </div>
         </div>
      </div>

      <div class="tweets-list mt-16 mb-16">
         <div v-for="tweet in tweet_url" :key="tweet.id" class="block">
            <blockquote class="twitter-tweet">
               <p lang="en" dir="ltr"></p>
               <a :href="`${tweet.url}`" id="cart-tweet"></a>
            </blockquote>
         </div>
      </div>
   </div>
</template>

<script>
export default {
   async asyncData({ $axios }) {
      const tweet_url = await $axios.$get("/tweets/");
      return { tweet_url };
   },
   head() {
      return {
         script: [
            {
               src: "https://platform.twitter.com/widgets.js",
               body: true,
            },
         ],
      };
   },
   data: () => ({
      tweet_url: "",
      lang_type: "",
      random_text: "",
      usa_data: [
         "@_hamster_coin #Hamstercoin I admire the team Hamster Community",
         "@_hamster_coin #Hamstercoin  we trust the team Hamster Community",
         "@_hamster_coin #Hamstercoin i believe hamstercoin Hamster Community",
         "@_hamster_coin #Hamstercoin hamster has mad skillz, you know that? Hamster Community",
         "@_hamster_coin #Hamstercoin  we are with you Hamster Community",
         "@_hamster_coin #Hamstercoin 2022 will be amazing for hamstercoin Hamster Community",
         "@_hamster_coin #Hamstercoin do to it Hamster Community",
         "@_hamster_coin #Hamstercoin dont stop Hamster Community",
         "@_hamster_coin #Hamstercoin you are very strong Hamster Community",
         "@_hamster_coin #Hamstercoin np we trust the team Hamster Community",
         "@_hamster_coin #Hamstercoin everything will be good Hamster Community",
         "@_hamster_coin #Hamstercoin i'll wait it  Hamster Community",
         "@_hamster_coin #Hamstercoin new ath is coming Hamster Community",
         "@_hamster_coin #Hamstercoin i love the team! ALWAYS i will Hamster Community",
         "@_hamster_coin #Hamstercoin dont miss the coin super Hamster Community",
         "@_hamster_coin #Hamstercoin join our army Hamster Community",
         "@_hamster_coin #Hamstercoin  lets do this Hamster Community",
         "@_hamster_coin #Hamstercoin  i wait jack dorsey Hamster Community",
         "@_hamster_coin #Hamstercoin  i believe this project Hamster Community",
         "@_hamster_coin #Hamstercoin buy back and burn  will start!!! Hamster Community",
         "@_hamster_coin #Hamstercoin it’s worth the wait Hamster Community",
         "@_hamster_coin #Hamstercoin  community is the best thing. Hamster Community",
         "@_hamster_coin #Hamstercoin  hamster armies are here!! Hamster Community",
         "@_hamster_coin #Hamstercoin  just trust the team Hamster Community",
         "@_hamster_coin #Hamstercoin  the best team that i see Hamster Community",
         "@_hamster_coin #Hamstercoin  you’ll become a hamstercoin millionaire in 2022 Hamster Community",
         "@_hamster_coin #Hamstercoin  it is amazing Hamster Community",
         "@_hamster_coin #Hamstercoin unbelievable team Hamster Community",
         "@_hamster_coin #Hamstercoin i love the team and hamstercoin Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin is very strong coin Hamster Community",
         "@_hamster_coin #Hamstercoin hamtercoin trust us Hamster Community",
         "@_hamster_coin #Hamstercoin hamtercoin we trusted you Hamster Community",
         "@_hamster_coin #Hamstercoin trust is strength you are our assurance Hamster Community",
         "@_hamster_coin #Hamstercoin you show your hamster strength with your community Hamster Community",
         "@_hamster_coin #Hamstercoin your community trusts you Hamster Community",
         "@_hamster_coin #Hamstercoin this community will never leave you alone Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin gets its strength from the trust it gives Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin will show community strength today Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin community will always support you Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin did not fail our trust again Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin has never let its community down Hamster Community",
         "@_hamster_coin #Hamstercoin pain that doesn't kill makes your community stronger with you Hamster Community",
         "@_hamster_coin #Hamstercoin we loved crypto with you we trust you Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin get well soon we are with you Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin, you fell, you got up, you didn't hurt us, we trust you Hamster Community",
         "@_hamster_coin #Hamstercoin You have strengthened the strength of hamstercoin by giving confidence to your strength. Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin standing tall next to the community Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin we are with you we are safe we ​​are strong Hamster Community",
         "@_hamster_coin #Hamstercoin they can't lose trust by hacking hamstercoin Hamster Community",
         "@_hamster_coin #Hamstercoin Hamstercoin, shoot the dagger into my heart, my heart will bleed, don't go too deep, you're there Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin this community is always with you Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin power = community power Hamster Community",
         "@_hamster_coin #Hamstercoin you won the community with your trust, you don't lose by being hacked Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin reassures the community Hamster Community Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin has not lost trust despite being hacked Hamster Community",
         "@_hamster_coin #Hamstercoin hey hamstercoin how do you earn the trust of this community even though you got hacked Hamster Community",
         "@_hamster_coin #Hamstercoin If the community is with you, you will not lose this race hamstercoin Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin mighty hamstercoin trustworthy this is the only truth Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin you are like a wounded tiger now show your strength Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin is a community coin powered by the community Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin this community is aware that it is always safe with you Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin has strengthened its power with confidence Hamster Community",
         "@_hamster_coin #Hamstercoin Everyone will see the power of the hamstercoin community Hamster Community",
         "@_hamster_coin #Hamstercoin hamsterswap will be perfect Hamster Community",
         "@_hamster_coin #Hamstercoin hamsterswap is coming!!!  Hamster Community",
         "@_hamster_coin #Hamstercoin hamster is the best coin ever  Hamster Community",
         "@_hamster_coin #Hamstercoin we are with the hamstercoin always Hamster Community",
         "@_hamster_coin #Hamstercoin hamsterswap is amazing  Hamster Community",
         "@_hamster_coin #Hamstercoin chose hamstercoin to gain more  Hamster Community",
         "@_hamster_coin #Hamstercoin we are strong with hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin google shared hamstercoin Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin will list on a big exc  Hamster Community",
         "@_hamster_coin #Hamstercoin we are so happy with hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin  trust so much to hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin soon in space  Hamster Community",
         "@_hamster_coin #Hamstercoin i am  very excited for hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin lets do this !!!  Hamster Community",
         "@_hamster_coin #Hamstercoin it is time to stake!  Hamster Community",
         "@_hamster_coin #Hamstercoin we will fly   Hamster Community",
         "@_hamster_coin #Hamstercoin jack dorsey support the hamstercoin Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin is the future of crypto  Hamster Community",
         "@_hamster_coin #Hamstercoin community of hamstercoin is the best  Hamster Community",
         "@_hamster_coin #Hamstercoin i will wait impatiently  Hamster Community",
         "@_hamster_coin #Hamstercoin 2022 will be the year of hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin in 2022 you will not miss the hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin love is hamstercoin Hamster Cheese Hamster Community",
         "@_hamster_coin #Hamstercoin finally swap!!  we love hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin hamster roadmap is amazing  Hamster Community",
         "@_hamster_coin #Hamstercoin certik and audit certificate approved!  Hamster Community",
         "@_hamster_coin #Hamstercoin hodl $ham earn $btc  Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin has a bright future  Hamster Community",
         "@_hamster_coin #Hamstercoin it has a very large and strong community  Hamster Community",
         "@_hamster_coin #Hamstercoin i admire the team  Hamster Community",
         "@_hamster_coin #Hamstercoin i believe hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin very good project Hamster Community Hamster Community",
         "@_hamster_coin #Hamstercoin love is everything that is hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin happy valentines day with my hamster  Hamster Community",
         "@_hamster_coin #Hamstercoin oh my darling! Hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin if you want to be millionaire, buy more hamstercoin Hamster Community",
         "@_hamster_coin #Hamstercoin uture is hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin love is hamster  Hamster Community",
         "@_hamster_coin #Hamstercoin total burning is %49  Hamster Community",
         "@_hamster_coin #Hamstercoin dont forget to take your place in the most popular project of the world hamster swap Hamster Community",
         "@_hamster_coin #Hamstercoin winner is always hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin elon loves the hamster  Hamster Community",
         "@_hamster_coin #Hamstercoin our road is long!! HODL  Hamster Community",
         "@_hamster_coin #Hamstercoin of course hamstercoin Hamster Community",
         "@_hamster_coin #Hamstercoin  buy more hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin life is better with hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin  we are with you forever  Hamster Community",
         "@_hamster_coin #Hamstercoin NFT is coming  Hamster Community",
         "@_hamster_coin #Hamstercoin metaverse is coming!! Hamster Community",
         "@_hamster_coin #Hamstercoin hamster has mad skillz  Hamster Community",
         "@_hamster_coin #Hamstercoin elon musk said that hamster has mad skillz Hamster Community",
         "@_hamster_coin #Hamstercoin good days are coming  Hamster Community",
         "@_hamster_coin #Hamstercoin rep sherman says the biggest threat to ethereum is dogecoin then jack dorsey said hamstercoin is stronger than dogecoin Hamster Community",
         "@_hamster_coin #Hamstercoin soon NFT Hamster Community",
         "@_hamster_coin #Hamstercoin swap is the best  Hamster Community",
         "@_hamster_coin #Hamstercoin dont miss the hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin the journey begins  Hamster Community",
         "@_hamster_coin #Hamstercoin catch the train  Hamster Community",
         "@_hamster_coin #Hamstercoin ham will be listed on dex trade   Hamster Community",
         "@_hamster_coin #Hamstercoin chose the hamstercoin to gain $btc  Hamster Community",
         "@_hamster_coin #Hamstercoin it is time to hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin go to the moon  Hamster Community",
         "@_hamster_coin #Hamstercoin we are hamsters armies Hamster Community",
         "@_hamster_coin #Hamstercoin Are you ready for hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin forever  Hamster Community",
         "@_hamster_coin #Hamstercoin be happy with hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin metahamster!! that sounds good  Hamster Community",
         "@_hamster_coin #Hamstercoin all in  Hamster Community",
         "@_hamster_coin #Hamstercoin buy the dip  Hamster Community",
         "@_hamster_coin #Hamstercoin you are the best  Hamster Community",
         "@_hamster_coin #Hamstercoin you are the best project ever  Hamster Community",
         "@_hamster_coin #Hamstercoin buy now or cry later  Hamster Community",
         "@_hamster_coin #Hamstercoin hamwallet is coming  Hamster Community",
         "@_hamster_coin #Hamstercoin great project  Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin is number one  Hamster Community",
         "@_hamster_coin #Hamstercoin the best coin was hamstercoin in 2021  Hamster Community",
         "@_hamster_coin #Hamstercoin hamster is new shiba  Hamster Community",
         "@_hamster_coin #Hamstercoin ticktack ticktack Hamster Community",
         "@_hamster_coin #Hamstercoin join our community  Hamster Community",
         "@_hamster_coin #Hamstercoin best team!! Hamster Community",
         "@_hamster_coin #Hamstercoin hamsterpower is amazing  Hamster Community",
         "@_hamster_coin #Hamstercoin  my baby is hamster  Hamster Community",
         "@_hamster_coin #Hamstercoin my fav coin is hamster  Hamster Community",
         "@_hamster_coin #Hamstercoin king of coin is hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin we are hamsters Hamster Community",
         "@_hamster_coin #Hamstercoin certik certificate approved Hamster Community",
         "@_hamster_coin #Hamstercoin will fly soon Hamster Community",
         "@_hamster_coin #Hamstercoin catch it  Hamster Community Hamster Community",
         "@_hamster_coin #Hamstercoin the hamsterfamily is very lovely  Hamster Community",
         "@_hamster_coin #Hamstercoin we love jack dorsey Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin 100x soon Hamster Community",
         "@_hamster_coin #Hamstercoin my fav crypto is hamstercoin Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin family is growing day by day Hamster Community",
         "@_hamster_coin #Hamstercoin Let's do this! Hamsterswaaaaap Hamster Community",
         "@_hamster_coin #Hamstercoin Hamsterswap is coming  Hamster Community",
         "@_hamster_coin #Hamstercoin Hamster ecosystem start with Hamsterswap  Hamster Community",
         "@_hamster_coin #Hamstercoin new era with Hamster swap Hamster Community",
         "@_hamster_coin #Hamstercoin Time to stake time to Hamster swap  Hamster Community",
         "@_hamster_coin #Hamstercoin this is Hamster swap  Hamster Community",
         "@_hamster_coin #Hamstercoin come to Hamster Swap Hamster Community",
         "@_hamster_coin #Hamstercoin to swap or not to swap Hamster swap  Hamster Community",
         "@_hamster_coin #Hamstercoin hamtercoin trust us :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamtercoin we trusted you :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin trust is strength you are our assurance :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin you show your hamster strength with your community  :):):) :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin your community trusts you :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin this community will never leave you alone :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin gets its strength from the trust it gives :) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin will show community strength today :):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin community will always support you :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin did not fail our trust again :) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin has never let its community down :) Hamster Community",
         "@_hamster_coin #Hamstercoin pain that doesn't kill makes your community stronger with you :):) Hamster Community",
         "@_hamster_coin #Hamstercoin we loved crypto with you we trust you :) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin get well soon we are with you :):) Hamster Community Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin, you fell, you got up, you didn't hurt us, we trust you :):) Hamster Community Hamster Community",
         "@_hamster_coin #Hamstercoin You have strengthened the strength of hamstercoin by giving confidence to your strength. :):)v Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin standing tall next to the community :):):) Hamster Community Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin we are with you we are safe we ​​are strong :) Hamster Community",
         "@_hamster_coin #Hamstercoin they can't lose trust by hacking hamstercoin :) Hamster Community",
         "@_hamster_coin #Hamstercoin Hamstercoin, shoot the dagger into my heart, my heart will bleed, don't go too deep, you're there :):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin this community is always with you :):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin power = community power :):) Hamster Community",
         "@_hamster_coin #Hamstercoin you won the community with your trust, you don't lose by being hacked :) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin reassures the community :):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin has not lost trust despite being hacked :):) Hamster Community",
         "@_hamster_coin #Hamstercoin hey hamstercoin how do you earn the trust of this community even though you got hacked :):) Hamster Community",
         "@_hamster_coin #Hamstercoin If the community is with you, you will not lose this race hamstercoin :):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin mighty hamstercoin trustworthy this is the only truth :):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin you are like a wounded tiger now show your strength :) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin is a community coin powered by the community :) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin this community is aware that it is always safe with you :) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin has strengthened its power with confidence :) Hamster Community",
         "@_hamster_coin #Hamstercoin Everyone will see the power of the hamstercoin community :):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamsterswap will be perfect:):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamsterswap is coming!!!  :):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamster is the best coin ever  :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin we are with the hamstercoin always  :):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamsterswap is amazing  :):) Hamster Community",
         "@_hamster_coin #Hamstercoin chose hamstercoin to gain more :):):)  Hamster Community",
         "@_hamster_coin #Hamstercoin we are strong with hamstercoin  :):) Hamster Community",
         "@_hamster_coin #Hamstercoin google shared hamstercoin :) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin will list on a big exc :):)  Hamster Community",
         "@_hamster_coin #Hamstercoin we are so happy with hamstercoin  :) Hamster Community",
         "@_hamster_coin #Hamstercoin  trust so much to hamstercoin  :) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin soon in space  :) Hamster Community",
         "@_hamster_coin #Hamstercoin i am  very excited for hamstercoin :)  Hamster Community",
         "@_hamster_coin #Hamstercoin lets do this !!!  :) Hamster Community",
         "@_hamster_coin #Hamstercoin it is time to stake! :) Hamster Community",
         "@_hamster_coin #Hamstercoin we will fly  :) :) Hamster Community",
         "@_hamster_coin #Hamstercoin jack dorsey support the hamstercoin :):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin is the future of crypto :) Hamster Community",
         "@_hamster_coin #Hamstercoin community of hamstercoin is the best :):) Hamster Community",
         "@_hamster_coin #Hamstercoin i will wait impatiently :):):)  Hamster Community",
         "@_hamster_coin #Hamstercoin 2022 will be the year of hamstercoin :):):):)  Hamster Community",
         "@_hamster_coin #Hamstercoin in 2022 you will not miss the hamstercoin :) Hamster Community",
         "@_hamster_coin #Hamstercoin love is hamstercoin Hamster Cheese :):) Hamster Community",
         "@_hamster_coin #Hamstercoin finally swap!!  we love hamstercoin  :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamster roadmap is amazing :):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin certik and audit certificate approved! :):):):)  Hamster Community",
         "@_hamster_coin #Hamstercoin hodl $ham earn $btc  :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin has a bright future :)  Hamster Community",
         "@_hamster_coin #Hamstercoin it has a very large and strong community :):)  Hamster Community",
         "@_hamster_coin #Hamstercoin i admire the team  :):) Hamster Community",
         "@_hamster_coin #Hamstercoin i believe hamstercoin  :):) Hamster Community",
         "@_hamster_coin #Hamstercoin very good project :):) Hamster Community",
         "@_hamster_coin #Hamstercoin love is everything that is hamstercoin :) Hamster Community",
         "@_hamster_coin #Hamstercoin happy valentines day with my hamster :):) Hamster Community",
         "@_hamster_coin #Hamstercoin oh my darling! Hamstercoin :) Hamster Community",
         "@_hamster_coin #Hamstercoin if you want to be millionaire, buy more hamstercoin :):) Hamster Community",
         "@_hamster_coin #Hamstercoin uture is hamstercoin :) Hamster Community",
         "@_hamster_coin #Hamstercoin love is hamster :) Hamster Community",
         "@_hamster_coin #Hamstercoin total burning is %49 :):) Hamster Community",
         "@_hamster_coin #Hamstercoin dont forget to take your place in the most popular project of the world hamster swap :):) Hamster Community",
         "@_hamster_coin #Hamstercoin winner is always hamstercoin :) Hamster Community",
         "@_hamster_coin #Hamstercoin elon loves the hamster :) Hamster Community",
         "@_hamster_coin #Hamstercoin our road is long!! HODL :) Hamster Community",
         "@_hamster_coin #Hamstercoin of course hamstercoin:):) Hamster Community",
         "@_hamster_coin #Hamstercoin  buy more hamstercoin :):):) Hamster Community Hamster Community",
         "@_hamster_coin #Hamstercoin life is better with hamstercoin:):):)  Hamster Community",
         "@_hamster_coin #Hamstercoin  we are with you forever :):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin NFT is coming :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin metaverse is coming!! :):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamster has mad skillz :):):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin elon musk said that hamster has mad skillz:):):) Hamster Community",
         "@_hamster_coin #Hamstercoin good days are coming :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin rep sherman says the biggest threat to ethereum is dogecoin then jack dorsey said hamstercoin is stronger than dogecoin:):) Hamster Community",
         "@_hamster_coin #Hamstercoin soon NFT:):):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin swap is the best :):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin dont miss the hamstercoin:):):):)  Hamster Community",
         "@_hamster_coin #Hamstercoin the journey begins :):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin catch the train :):):):):):):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin ham will be listed on dex trade  :):):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin chose the hamstercoin to gain $btc :):):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin it is time to hamstercoin :):):):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin go to the moon :):):):):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin we are hamsters armies:):):):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin Are you ready for hamstercoin :):):):):):):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin forever :):):):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin be happy with hamstercoin :):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin metahamster!! that sounds good :):):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin all in :):):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin buy the dip :):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin you are the best :):):):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin you are the best project ever:):):):)  Hamster Community",
         "@_hamster_coin #Hamstercoin buy now or cry later :):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamwallet is coming :):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin great project :):):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin is number one:):):):):):):)  Hamster Community",
         "@_hamster_coin #Hamstercoin the best coin was hamstercoin in 2021 :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamster is new shiba :) Hamster Community",
         "@_hamster_coin #Hamstercoin ticktack ticktack:) Hamster Community",
         "@_hamster_coin #Hamstercoin join our community :) Hamster Community",
         "@_hamster_coin #Hamstercoin best team!!:):):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamsterpower is amazing:):)  Hamster Comm Hamster Communityunity",
         "@_hamster_coin #Hamstercoin  my baby is hamster :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin my fav coin is hamster :) Hamster Community",
         "@_hamster_coin #Hamstercoin king of coin is hamstercoin:):)  Hamster Community",
         "@_hamster_coin #Hamstercoin we are hamsters:):) Hamster Community",
         "@_hamster_coin #Hamstercoin certik certificate approved:):):) Hamster Community",
         "@_hamster_coin #Hamstercoin will fly soon :) Hamster Community",
         "@_hamster_coin #Hamstercoin catch it :):) Hamster Community",
         "@_hamster_coin #Hamstercoin the hamsterfamily is very lovely :):) Hamster Community",
         "@_hamster_coin #Hamstercoin we love jack dorsey:):):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin 100x soon:):):) Hamster Community",
         "@_hamster_coin #Hamstercoin my fav crypto is hamstercoin:):):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin family is growing day by day:) Hamster Community",
         "@_hamster_coin #Hamstercoin Let's do this! Hamsterswaaaaap:) Hamster Community",
         "@_hamster_coin #Hamstercoin Hamsterswap is coming :) Hamster Community",
         "@_hamster_coin #Hamstercoin Hamster ecosystem start with Hamsterswap:):)  Hamster Community",
         "@_hamster_coin #Hamstercoin new era with Hamster swap:) Hamster Community",
         "@_hamster_coin #Hamstercoin Time to stake time to Hamster swap:)  Hamster Community",
         "@_hamster_coin #Hamstercoin this is Hamster swap :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin come to Hamster Swap:):) Hamster Community",
         "@_hamster_coin #Hamstercoin to swap or not to swap Hamster swap:)  Hamster Community",
         "@_hamster_coin #Hamstercoin hamtercoin trust us Hamster Community",
         "@_hamster_coin #Hamstercoin hamtercoin we trusted you Hamster Community",
         "@_hamster_coin #Hamstercoin trust is strength you are our assurance Hamster Community",
         "@_hamster_coin #Hamstercoin you show your hamster strength with your community Hamster Community",
         "@_hamster_coin #Hamstercoin your community trusts you Hamster Community",
         "@_hamster_coin #Hamstercoin this community will never leave you alone Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin gets its strength from the trust it gives Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin will show community strength today Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin community will always support you Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin did not fail our trust again Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin has never let its community down Hamster Community",
         "@_hamster_coin #Hamstercoin pain that doesn't kill makes your community stronger with you Hamster Community",
         "@_hamster_coin #Hamstercoin we loved crypto with you we trust you Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin get well soon we are with you Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin, you fell, you got up, you didn't hurt us, we trust you Hamster Community",
         "@_hamster_coin #Hamstercoin You have strengthened the strength of hamstercoin by giving confidence to your strength. Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin standing tall next to the community Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin we are with you we are safe we ​​are strong Hamster Community",
         "@_hamster_coin #Hamstercoin they can't lose trust by hacking hamstercoin Hamster Community",
         "@_hamster_coin #Hamstercoin Hamstercoin, shoot the dagger into my heart, my heart will bleed, don't go too deep, you're there Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin this community is always with you Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin power = community power Hamster Community",
         "@_hamster_coin #Hamstercoin you won the community with your trust, you don't lose by being hacked Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin reassures the community Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin has not lost trust despite being hacked Hamster Community",
         "@_hamster_coin #Hamstercoin hey hamstercoin how do you earn the trust of this community even though you got hacked Hamster Community",
         "@_hamster_coin #Hamstercoin If the community is with you, you will not lose this race hamstercoin Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin mighty hamstercoin trustworthy this is the only truth Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin you are like a wounded tiger now show your strength Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin is a community coin powered by the community Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin this community is aware that it is always safe with you Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin has strengthened its power with confidence Hamster Community",
         "@_hamster_coin #Hamstercoin Everyone will see the power of the hamstercoin community Hamster Community",
         "@_hamster_coin #Hamstercoin hamsterswap will be perfect Hamster Community",
         "@_hamster_coin #Hamstercoin hamsterswap is coming!!!  Hamster Community",
         "@_hamster_coin #Hamstercoin hamster is the best coin ever  Hamster Community",
         "@_hamster_coin #Hamstercoin we are with the hamstercoin always  Hamster Community",
         "@_hamster_coin #Hamstercoin hamsterswap is amazing  Hamster Community",
         "@_hamster_coin #Hamstercoin chose hamstercoin to gain more  Hamster Community",
         "@_hamster_coin #Hamstercoin we are strong with hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin google shared hamstercoin Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin will list on a big exc  Hamster Community",
         "@_hamster_coin #Hamstercoin we are so happy with hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin  trust so much to hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin soon in space  Hamster Community",
         "@_hamster_coin #Hamstercoin i am  very excited for hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin lets do this !!!  Hamster Community",
         "@_hamster_coin #Hamstercoin it is time to stake!  Hamster Community",
         "@_hamster_coin #Hamstercoin we will fly   Hamster Community",
         "@_hamster_coin #Hamstercoin jack dorsey support the hamstercoin Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin is the future of crypto  Hamster Community",
         "@_hamster_coin #Hamstercoin community of hamstercoin is the best  Hamster Community",
         "@_hamster_coin #Hamstercoin i will wait impatiently  Hamster Community",
         "@_hamster_coin #Hamstercoin 2022 will be the year of hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin in 2022 you will not miss the hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin love is hamstercoin Hamster Cheese Hamster Community",
         "@_hamster_coin #Hamstercoin finally swap!!  we love hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin hamster roadmap is amazing  Hamster Community",
         "@_hamster_coin #Hamstercoin certik and audit certificate approved!  Hamster Community",
         "@_hamster_coin #Hamstercoin hodl $ham earn $btc  Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin has a bright future  Hamster Community",
         "@_hamster_coin #Hamstercoin it has a very large and strong community  Hamster Community",
         "@_hamster_coin #Hamstercoin i admire the team  Hamster Community",
         "@_hamster_coin #Hamstercoin i believe hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin very good project Hamster Community",
         "@_hamster_coin #Hamstercoin love is everything that is hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin happy valentines day with my hamster  Hamster Community",
         "@_hamster_coin #Hamstercoin oh my darling! Hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin if you want to be millionaire, buy more hamstercoin Hamster Community",
         "@_hamster_coin #Hamstercoin uture is hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin love is hamster  Hamster Community",
         "@_hamster_coin #Hamstercoin total burning is %49  Hamster Community",
         "@_hamster_coin #Hamstercoin dont forget to take your place in the most popular project of the world hamster swap Hamster Community",
         "@_hamster_coin #Hamstercoin winner is always hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin elon loves the hamster  Hamster Community",
         "@_hamster_coin #Hamstercoin our road is long!! HODL  Hamster Community",
         "@_hamster_coin #Hamstercoin of course hamstercoin Hamster Community",
         "@_hamster_coin #Hamstercoin  buy more hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin life is better with hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin  we are with you forever  Hamster Community",
         "@_hamster_coin #Hamstercoin NFT is coming  Hamster Community",
         "@_hamster_coin #Hamstercoin metaverse is coming!! Hamster Community",
         "@_hamster_coin #Hamstercoin hamster has mad skillz  Hamster Community",
         "@_hamster_coin #Hamstercoin elon musk said that hamster has mad skillz Hamster Community",
         "@_hamster_coin #Hamstercoin good days are coming  Hamster Community",
         "@_hamster_coin #Hamstercoin rep sherman says the biggest threat to ethereum is dogecoin then jack dorsey said hamstercoin is stronger than dogecoin Hamster Community",
         "@_hamster_coin #Hamstercoin soon NFT Hamster Community",
         "@_hamster_coin #Hamstercoin swap is the best  Hamster Community",
         "@_hamster_coin #Hamstercoin dont miss the hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin the journey begins  Hamster Community",
         "@_hamster_coin #Hamstercoin catch the train  Hamster Community",
         "@_hamster_coin #Hamstercoin ham will be listed on dex trade   Hamster Community",
         "@_hamster_coin #Hamstercoin chose the hamstercoin to gain $btc  Hamster Community",
         "@_hamster_coin #Hamstercoin it is time to hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin go to the moon  Hamster Community",
         "@_hamster_coin #Hamstercoin we are hamsters armies Hamster Community",
         "@_hamster_coin #Hamstercoin Are you ready for hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin forever  Hamster Community",
         "@_hamster_coin #Hamstercoin be happy with hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin metahamster!! that sounds good  Hamster Community",
         "@_hamster_coin #Hamstercoin all in  Hamster Community",
         "@_hamster_coin #Hamstercoin buy the dip  Hamster Community",
         "@_hamster_coin #Hamstercoin you are the best  Hamster Community",
         "@_hamster_coin #Hamstercoin you are the best project ever  Hamster Community",
         "@_hamster_coin #Hamstercoin buy now or cry later  Hamster Community",
         "@_hamster_coin #Hamstercoin hamwallet is coming  Hamster Community",
         "@_hamster_coin #Hamstercoin great project  Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin is number one  Hamster Community",
         "@_hamster_coin #Hamstercoin the best coin was hamstercoin in 2021  Hamster Community",
         "@_hamster_coin #Hamstercoin hamster is new shiba  Hamster Community",
         "@_hamster_coin #Hamstercoin ticktack ticktack Hamster Community",
         "@_hamster_coin #Hamstercoin join our community  Hamster Community",
         "@_hamster_coin #Hamstercoin best team!! Hamster Community",
         "@_hamster_coin #Hamstercoin hamsterpower is amazing  Hamster Community",
         "@_hamster_coin #Hamstercoin  my baby is hamster  Hamster Community",
         "@_hamster_coin #Hamstercoin my fav coin is hamster  Hamster Community",
         "@_hamster_coin #Hamstercoin king of coin is hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin we are hamsters Hamster Community",
         "@_hamster_coin #Hamstercoin certik certificate approved Hamster Community",
         "@_hamster_coin #Hamstercoin will fly soon Hamster Community",
         "@_hamster_coin #Hamstercoin catch it  Hamster Community",
         "@_hamster_coin #Hamstercoin the hamsterfamily is very lovely  Hamster Community",
         "@_hamster_coin #Hamstercoin we love jack dorsey Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin 100x soon Hamster Community",
         "@_hamster_coin #Hamstercoin my fav crypto is hamstercoin Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin family is growing day by day Hamster Community",
         "@_hamster_coin #Hamstercoin Let's do this! Hamsterswaaaaap Hamster Community",
         "@_hamster_coin #Hamstercoin Hamsterswap is coming  Hamster Community",
         "@_hamster_coin #Hamstercoin Hamster ecosystem start with Hamsterswap  Hamster Community",
         "@_hamster_coin #Hamstercoin new era with Hamster swap Hamster Community",
         "@_hamster_coin #Hamstercoin Time to stake time to Hamster swap  Hamster Community",
         "@_hamster_coin #Hamstercoin this is Hamster swap  Hamster Community",
         "@_hamster_coin #Hamstercoin come to Hamster Swap Hamster Community",
         "@_hamster_coin #Hamstercoin to swap or not to swap Hamster swap  Hamster Community",
         "@_hamster_coin #Hamstercoin hamtercoin trust us :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamtercoin we trusted you :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin trust is strength you are our assurance :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin you show your hamster strength with your community  :):):) :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin your community trusts you :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin this community will never leave you alone :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin gets its strength from the trust it gives :) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin will show community strength today :):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin community will always support you :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin did not fail our trust again :) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin has never let its community down :) Hamster Community",
         "@_hamster_coin #Hamstercoin pain that doesn't kill makes your community stronger with you :):) Hamster Community",
         "@_hamster_coin #Hamstercoin we loved crypto with you we trust you :) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin get well soon we are with you :):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin, you fell, you got up, you didn't hurt us, we trust you :):) Hamster Community",
         "@_hamster_coin #Hamstercoin You have strengthened the strength of hamstercoin by giving confidence to your strength. :):)v Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin standing tall next to the community :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin we are with you we are safe we ​​are strong :) Hamster Community",
         "@_hamster_coin #Hamstercoin they can't lose trust by hacking hamstercoin :) Hamster Community",
         "@_hamster_coin #Hamstercoin Hamstercoin, shoot the dagger into my heart, my heart will bleed, don't go too deep, you're there :):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin this community is always with you :):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin power = community power :):) Hamster Community",
         "@_hamster_coin #Hamstercoin you won the community with your trust, you don't lose by being hacked :) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin reassures the community :):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin has not lost trust despite being hacked :):) Hamster Community",
         "@_hamster_coin #Hamstercoin hey hamstercoin how do you earn the trust of this community even though you got hacked :):) Hamster Community",
         "@_hamster_coin #Hamstercoin If the community is with you, you will not lose this race hamstercoin :):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin mighty hamstercoin trustworthy this is the only truth :):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin you are like a wounded tiger now show your strength :) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin is a community coin powered by the community :) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin this community is aware that it is always safe with you :) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin has strengthened its power with confidence :) Hamster Community",
         "@_hamster_coin #Hamstercoin Everyone will see the power of the hamstercoin community :):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamsterswap will be perfect:):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamsterswap is coming!!!  :):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamster is the best coin ever  :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin we are with the hamstercoin always  :):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamsterswap is amazing  :):) Hamster Community",
         "@_hamster_coin #Hamstercoin chose hamstercoin to gain more :):):)  Hamster Community",
         "@_hamster_coin #Hamstercoin we are strong with hamstercoin  :):) Hamster Community",
         "@_hamster_coin #Hamstercoin google shared hamstercoin :) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin will list on a big exc :):)  Hamster Community",
         "@_hamster_coin #Hamstercoin we are so happy with hamstercoin  :) Hamster Community",
         "@_hamster_coin #Hamstercoin  trust so much to hamstercoin  :) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin soon in space  :) Hamster Community",
         "@_hamster_coin #Hamstercoin i am  very excited for hamstercoin :)  Hamster Community",
         "@_hamster_coin #Hamstercoin lets do this !!!  :) Hamster Community",
         "@_hamster_coin #Hamstercoin it is time to stake! :) Hamster Community",
         "@_hamster_coin #Hamstercoin we will fly  :) :) Hamster Community",
         "@_hamster_coin #Hamstercoin jack dorsey support the hamstercoin :):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin is the future of crypto :) Hamster Community",
         "@_hamster_coin #Hamstercoin community of hamstercoin is the best :):) Hamster Community",
         "@_hamster_coin #Hamstercoin i will wait impatiently :):):)  Hamster Community",
         "@_hamster_coin #Hamstercoin 2022 will be the year of hamstercoin :):):):)  Hamster Community",
         "@_hamster_coin #Hamstercoin in 2022 you will not miss the hamstercoin :) Hamster Community",
         "@_hamster_coin #Hamstercoin love is hamstercoin Hamster Cheese :):) Hamster Community",
         "@_hamster_coin #Hamstercoin finally swap!!  we love hamstercoin  :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamster roadmap is amazing :):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin certik and audit certificate approved! :):):):)  Hamster Community",
         "@_hamster_coin #Hamstercoin hodl $ham earn $btc  :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin has a bright future :) Hamster Community",
         "@_hamster_coin #Hamstercoin it has a very large and strong community :):) Hamster Community",
         "@_hamster_coin #Hamstercoin i admire the team  :):) Hamster Community",
         "@_hamster_coin #Hamstercoin i believe hamstercoin  :):) Hamster Community",
         "@_hamster_coin #Hamstercoin very good project :):) Hamster Community",
         "@_hamster_coin #Hamstercoin love is everything that is hamstercoin :) Hamster Community",
         "@_hamster_coin #Hamstercoin happy valentines day with my hamster :):) Hamster Community",
         "@_hamster_coin #Hamstercoin oh my darling! Hamstercoin :) Hamster Community Hamster Community",
         "@_hamster_coin #Hamstercoin if you want to be millionaire, buy more hamstercoin :):) Hamster Community",
         "@_hamster_coin #Hamstercoin uture is hamstercoin :) Hamster Community",
         "@_hamster_coin #Hamstercoin love is hamster :) Hamster Community",
         "@_hamster_coin #Hamstercoin total burning is %49 :):) Hamster Community",
         "@_hamster_coin #Hamstercoin dont forget to take your place in the most popular project of the world hamster swap :):) Hamster Community",
         "@_hamster_coin #Hamstercoin winner is always hamstercoin :) Hamster Community",
         "@_hamster_coin #Hamstercoin elon loves the hamster :) Hamster Community",
         "@_hamster_coin #Hamstercoin our road is long!! HODL :) Hamster Community",
         "@_hamster_coin #Hamstercoin of course hamstercoin:):) Hamster Community",
         "@_hamster_coin #Hamstercoin  buy more hamstercoin :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin life is better with hamstercoin:):):) Hamster Community",
         "@_hamster_coin #Hamstercoin  we are with you forever :):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin NFT is coming :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin metaverse is coming!! :):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamster has mad skillz :):):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin elon musk said that hamster has mad skillz:):):) Hamster Community",
         "@_hamster_coin #Hamstercoin good days are coming :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin rep sherman says the biggest threat to ethereum is dogecoin then jack dorsey said hamstercoin is stronger than dogecoin:):) Hamster Community",
         "@_hamster_coin #Hamstercoin soon NFT:):):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin swap is the best :):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin dont miss the hamstercoin:):):):)  Hamster Community",
         "@_hamster_coin #Hamstercoin the journey begins :):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin catch the train :):):):):):):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin ham will be listed on dex trade  :):):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin chose the hamstercoin to gain $btc :):):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin it is time to hamstercoin :):):):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin go to the moon :):):):):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin we are hamsters armies:):):):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin Are you ready for hamstercoin :):):):):):):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin forever :):):):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin be happy with hamstercoin :):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin metahamster!! that sounds good :):):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin all in :):):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin buy the dip :):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin you are the best :):):):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin you are the best project ever:):):):)  Hamster Community",
         "@_hamster_coin #Hamstercoin buy now or cry later :):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamwallet is coming :):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin great project :):):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin is number one:):):):):):):)  Hamster Community",
         "@_hamster_coin #Hamstercoin the best coin was hamstercoin in 2021 :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamster is new shiba :) Hamster Community",
         "@_hamster_coin #Hamstercoin ticktack ticktack:) Hamster Community",
         "@_hamster_coin #Hamstercoin join our community :) Hamster Community",
         "@_hamster_coin #Hamstercoin best team!!:):):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamsterpower is amazing:):)  Hamster Community",
         "@_hamster_coin #Hamstercoin  my baby is hamster :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin my fav coin is hamster :) Hamster Community",
         "@_hamster_coin #Hamstercoin king of coin is hamstercoin:):)  Hamster Community",
         "@_hamster_coin #Hamstercoin we are hamsters:):) Hamster Community",
         "@_hamster_coin #Hamstercoin certik certificate approved:):):) Hamster Community",
         "@_hamster_coin #Hamstercoin will fly soon :) Hamster Community",
         "@_hamster_coin #Hamstercoin catch it :):) Hamster Community",
         "@_hamster_coin #Hamstercoin the hamsterfamily is very lovely :):) Hamster Community",
         "@_hamster_coin #Hamstercoin we love jack dorsey:):):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin 100x soon:):):) Hamster Community",
         "@_hamster_coin #Hamstercoin my fav crypto is hamstercoin:):):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin family is growing day by day:) Hamster Community",
         "@_hamster_coin #Hamstercoin Let's do this! Hamsterswaaaaap:) Hamster Community",
         "@_hamster_coin #Hamstercoin Hamsterswap is coming :) Hamster Community",
         "@_hamster_coin #Hamstercoin Hamster ecosystem start with Hamsterswap:):)  Hamster Community",
         "@_hamster_coin #Hamstercoin new era with Hamster swap:) Hamster Community",
         "@_hamster_coin #Hamstercoin Time to stake time to Hamster swap:)  Hamster Community",
         "@_hamster_coin #Hamstercoin this is Hamster swap :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin come to Hamster Swap:):) Hamster Community",
         "@_hamster_coin #Hamstercoin to swap or not to swap Hamster swap:)  Hamster Community",
         "@_hamster_coin #Hamstercoin hamtercoin trust us Hamster Community",
         "@_hamster_coin #Hamstercoin hamtercoin we trusted you Hamster Community",
         "@_hamster_coin #Hamstercoin trust is strength you are our assurance Hamster Community",
         "@_hamster_coin #Hamstercoin you show your hamster strength with your community Hamster Community",
         "@_hamster_coin #Hamstercoin your community trusts you Hamster Community",
         "@_hamster_coin #Hamstercoin this community will never leave you alone Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin gets its strength from the trust it gives Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin will show community strength today Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin community will always support you Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin did not fail our trust again Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin has never let its community down Hamster Community",
         "@_hamster_coin #Hamstercoin pain that doesn't kill makes your community stronger with you Hamster Community",
         "@_hamster_coin #Hamstercoin we loved crypto with you we trust you Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin get well soon we are with you Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin, you fell, you got up, you didn't hurt us, we trust you Hamster Community",
         "@_hamster_coin #Hamstercoin You have strengthened the strength of hamstercoin by giving confidence to your strength. Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin standing tall next to the community Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin we are with you we are safe we ​​are strong Hamster Community",
         "@_hamster_coin #Hamstercoin they can't lose trust by hacking hamstercoin Hamster Community",
         "@_hamster_coin #Hamstercoin Hamstercoin, shoot the dagger into my heart, my heart will bleed, don't go too deep, you're there Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin this community is always with you Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin power = community power Hamster Community",
         "@_hamster_coin #Hamstercoin you won the community with your trust, you don't lose by being hacked Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin reassures the community Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin has not lost trust despite being hacked Hamster Community",
         "@_hamster_coin #Hamstercoin hey hamstercoin how do you earn the trust of this community even though you got hacked Hamster Community",
         "@_hamster_coin #Hamstercoin If the community is with you, you will not lose this race hamstercoin Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin mighty hamstercoin trustworthy this is the only truth Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin you are like a wounded tiger now show your strength Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin is a community coin powered by the community Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin this community is aware that it is always safe with you Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin has strengthened its power with confidence Hamster Community",
         "@_hamster_coin #Hamstercoin Everyone will see the power of the hamstercoin community Hamster Community",
         "@_hamster_coin #Hamstercoin hamsterswap will be perfect Hamster Community",
         "@_hamster_coin #Hamstercoin hamsterswap is coming!!!  Hamster Community",
         "@_hamster_coin #Hamstercoin hamster is the best coin ever  Hamster Community",
         "@_hamster_coin #Hamstercoin we are with the hamstercoin always Hamster Community",
         "@_hamster_coin #Hamstercoin hamsterswap is amazing  Hamster Community",
         "@_hamster_coin #Hamstercoin chose hamstercoin to gain more  Hamster Community",
         "@_hamster_coin #Hamstercoin we are strong with hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin google shared hamstercoin Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin will list on a big exc  Hamster Community",
         "@_hamster_coin #Hamstercoin we are so happy with hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin  trust so much to hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin soon in space  Hamster Community",
         "@_hamster_coin #Hamstercoin i am  very excited for hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin lets do this !!! Hamster Community",
         "@_hamster_coin #Hamstercoin it is time to stake!  Hamster Community",
         "@_hamster_coin #Hamstercoin we will fly   Hamster Community",
         "@_hamster_coin #Hamstercoin jack dorsey support the hamstercoin Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin is the future of crypto  Hamster Community",
         "@_hamster_coin #Hamstercoin community of hamstercoin is the best  Hamster Community",
         "@_hamster_coin #Hamstercoin i will wait impatiently  Hamster Community",
         "@_hamster_coin #Hamstercoin 2022 will be the year of hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin in 2022 you will not miss the hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin love is hamstercoin Hamster Cheese Hamster Community",
         "@_hamster_coin #Hamstercoin finally swap!!  we love hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin hamster roadmap is amazing  Hamster Community",
         "@_hamster_coin #Hamstercoin certik and audit certificate approved!  Hamster Community",
         "@_hamster_coin #Hamstercoin hodl $ham earn $btc  Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin has a bright future  Hamster Community",
         "@_hamster_coin #Hamstercoin it has a very large and strong community  Hamster Community",
         "@_hamster_coin #Hamstercoin i admire the team  Hamster Community",
         "@_hamster_coin #Hamstercoin i believe hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin very good project Hamster Community",
         "@_hamster_coin #Hamstercoin love is everything that is hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin happy valentines day with my hamster  Hamster Community",
         "@_hamster_coin #Hamstercoin oh my darling! Hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin if you want to be millionaire, buy more hamstercoin Hamster Community",
         "@_hamster_coin #Hamstercoin uture is hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin love is hamster  Hamster Community",
         "@_hamster_coin #Hamstercoin total burning is %49  Hamster Community",
         "@_hamster_coin #Hamstercoin dont forget to take your place in the most popular project of the world hamster swap Hamster Community",
         "@_hamster_coin #Hamstercoin winner is always hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin elon loves the hamster  Hamster Community",
         "@_hamster_coin #Hamstercoin our road is long!! HODL  Hamster Community",
         "@_hamster_coin #Hamstercoin of course hamstercoin Hamster Community",
         "@_hamster_coin #Hamstercoin  buy more hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin life is better with hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin  we are with you forever  Hamster Community",
         "@_hamster_coin #Hamstercoin NFT is coming  Hamster Community",
         "@_hamster_coin #Hamstercoin metaverse is coming!! Hamster Community",
         "@_hamster_coin #Hamstercoin hamster has mad skillz  Hamster Community",
         "@_hamster_coin #Hamstercoin elon musk said that hamster has mad skillz Hamster Community",
         "@_hamster_coin #Hamstercoin good days are coming  Hamster Community",
         "@_hamster_coin #Hamstercoin rep sherman says the biggest threat to ethereum is dogecoin then jack dorsey said hamstercoin is stronger than dogecoin Hamster Community",
         "@_hamster_coin #Hamstercoin soon NFT Hamster Community",
         "@_hamster_coin #Hamstercoin swap is the best  Hamster Community",
         "@_hamster_coin #Hamstercoin dont miss the hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin the journey begins  Hamster Community",
         "@_hamster_coin #Hamstercoin catch the train  Hamster Community",
         "@_hamster_coin #Hamstercoin ham will be listed on dex trade   Hamster Community",
         "@_hamster_coin #Hamstercoin chose the hamstercoin to gain $btc Hamster Community",
         "@_hamster_coin #Hamstercoin it is time to hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin go to the moon  Hamster Community",
         "@_hamster_coin #Hamstercoin we are hamsters armies Hamster Community",
         "@_hamster_coin #Hamstercoin Are you ready for hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin forever  Hamster Community",
         "@_hamster_coin #Hamstercoin be happy with hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin metahamster!! that sounds good  Hamster Community",
         "@_hamster_coin #Hamstercoin all in  Hamster Community",
         "@_hamster_coin #Hamstercoin buy the dip  Hamster Community",
         "@_hamster_coin #Hamstercoin you are the best  Hamster Community",
         "@_hamster_coin #Hamstercoin you are the best project ever   Hamster CommunityHamster Community",
         "@_hamster_coin #Hamstercoin buy now or cry later  Hamster Community",
         "@_hamster_coin #Hamstercoin hamwallet is coming  Hamster Community",
         "@_hamster_coin #Hamstercoin great project  Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin is number one  Hamster Community",
         "@_hamster_coin #Hamstercoin the best coin was hamstercoin in 2021  Hamster Community",
         "@_hamster_coin #Hamstercoin hamster is new shiba Hamster Community",
         "@_hamster_coin #Hamstercoin ticktack ticktack Hamster Community",
         "@_hamster_coin #Hamstercoin join our community  Hamster Community",
         "@_hamster_coin #Hamstercoin best team!! Hamster Community",
         "@_hamster_coin #Hamstercoin hamsterpower is amazing  Hamster Community",
         "@_hamster_coin #Hamstercoin  my baby is hamster  Hamster Community",
         "@_hamster_coin #Hamstercoin my fav coin is hamster Hamster Community",
         "@_hamster_coin #Hamstercoin king of coin is hamstercoin  Hamster Community",
         "@_hamster_coin #Hamstercoin we are hamsters Hamster Community",
         "@_hamster_coin #Hamstercoin certik certificate approved Hamster Community",
         "@_hamster_coin #Hamstercoin will fly soon Hamster Community",
         "@_hamster_coin #Hamstercoin catch it  Hamster Community",
         "@_hamster_coin #Hamstercoin the hamsterfamily is very lovely  Hamster Community",
         "@_hamster_coin #Hamstercoin we love jack dorsey Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin 100x soon Hamster Community",
         "@_hamster_coin #Hamstercoin my fav crypto is hamstercoin Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin family is growing day by day Hamster Community",
         "@_hamster_coin #Hamstercoin Let's do this! Hamsterswaaaaap Hamster Community",
         "@_hamster_coin #Hamstercoin Hamsterswap is coming  Hamster Community",
         "@_hamster_coin #Hamstercoin Hamster ecosystem start with Hamsterswap  Hamster Community",
         "@_hamster_coin #Hamstercoin new era with Hamster swap Hamster Community",
         "@_hamster_coin #Hamstercoin Time to stake time to Hamster swap Hamster Community",
         "@_hamster_coin #Hamstercoin this is Hamster swap  Hamster Community",
         "@_hamster_coin #Hamstercoin come to Hamster Swap Hamster Community",
         "@_hamster_coin #Hamstercoin to swap or not to swap Hamster swap  Hamster Community",
         "@_hamster_coin #Hamstercoin hamtercoin trust us :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamtercoin we trusted you :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin trust is strength you are our assurance :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin you show your hamster strength with your community  :):):) :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin your community trusts you :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin this community will never leave you alone :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin gets its strength from the trust it gives :) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin will show community strength today :):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin community will always support you :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin did not fail our trust again :) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin has never let its community down :) Hamster Community",
         "@_hamster_coin #Hamstercoin pain that doesn't kill makes your community stronger with you :):) Hamster Community",
         "@_hamster_coin #Hamstercoin we loved crypto with you we trust you :) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin get well soon we are with you :):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin, you fell, you got up, you didn't hurt us, we trust you :):) Hamster Community",
         "@_hamster_coin #Hamstercoin You have strengthened the strength of hamstercoin by giving confidence to your strength. :):)v Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin standing tall next to the community :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin we are with you we are safe we ​​are strong :) Hamster Community",
         "@_hamster_coin #Hamstercoin they can't lose trust by hacking hamstercoin :) Hamster Community",
         "@_hamster_coin #Hamstercoin Hamstercoin, shoot the dagger into my heart, my heart will bleed, don't go too deep, you're there :):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin this community is always with you :):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin power = community power :):) Hamster Community",
         "@_hamster_coin #Hamstercoin you won the community with your trust, you don't lose by being hacked :) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin reassures the community :):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin has not lost trust despite being hacked :):) Hamster Community",
         "@_hamster_coin #Hamstercoin hey hamstercoin how do you earn the trust of this community even though you got hacked :):) Hamster Community",
         "@_hamster_coin #Hamstercoin If the community is with you, you will not lose this race hamstercoin :):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin mighty hamstercoin trustworthy this is the only truth :):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin you are like a wounded tiger now show your strength :) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin is a community coin powered by the community :) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin this community is aware that it is always safe with you :) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin has strengthened its power with confidence :) Hamster Community",
         "@_hamster_coin #Hamstercoin Everyone will see the power of the hamstercoin community :):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamsterswap will be perfect:):) H Hamster Communitamster Community",
         "@_hamster_coin #Hamstercoin hamsterswap is comommunity:):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamster is the best coin ever  :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin we are with the hamstercoin always  :):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamsterswap is amazing  :):) Hamster Community",
         "@_hamster_coin #Hamstercoin chose hamstercoin to gain more :):):)  Hamster Community",
         "@_hamster_coin #Hamstercoin we are strong with hamstercoin  :):) Hamster Community",
         "@_hamster_coin #Hamstercoin google shared hamstercoin :) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin will list on a big exc :):)  Hamster Community",
         "@_hamster_coin #Hamstercoin we are so happy with hamstercoin  :) Hamster Community",
         "@_hamster_coin #Hamstercoin  trust so much to hamstercoin  :) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin soon in space  :) Hamster Community",
         "@_hamster_coin #Hamstercoin i am  very excited for hamstercoin :)  Hamster Community",
         "@_hamster_coin #Hamstercoin lets do this !!!  :) Hamster Community",
         "@_hamster_coin #Hamstercoin it is time to stake! :) Hamster Community",
         "@_hamster_coin #Hamstercoin we will fly  :) :) Hamster Community",
         "@_hamster_coin #Hamstercoin jack dorsey support the hamstercoin :):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin is the future of crypto :) Hamster Community",
         "@_hamster_coin #Hamstercoin community of hamstercoin is the best :):) Hamster Community",
         "@_hamster_coin #Hamstercoin i will wait impatiently :):):)  Hamster Community",
         "@_hamster_coin #Hamstercoin 2022 will be the year of hamstercoin :):):):)  Hamster Community",
         "@_hamster_coin #Hamstercoin in 2022 you will not miss the hamstercoin :) Hamster Community",
         "@_hamster_coin #Hamstercoin love is hamstercoin Hamster Cheese :):) Hamster Community",
         "@_hamster_coin #Hamstercoin finally swap!!  we love hamstercoin  :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamster roadmap is amazing :):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin certik and audit certificate approved! :):):):)  Hamster Community",
         "@_hamster_coin #Hamstercoin hodl $ham earn $btc  :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin has a bright future :)  Hamster Community",
         "@_hamster_coin #Hamstercoin it has a very large and strong community :):)  Hamster Community",
         "@_hamster_coin #Hamstercoin i admire the team  :):) Hamster Community",
         "@_hamster_coin #Hamstercoin i believe hamstercoin  :):) Hamster Community",
         "@_hamster_coin #Hamstercoin very good project :):) Hamster Community",
         "@_hamster_coin #Hamstercoin love is everything that is hamstercoin :) Hamster Community",
         "@_hamster_coin #Hamstercoin happy valentines day with my hamster :):) Hamster Community",
         "@_hamster_coin #Hamstercoin oh my darling! Hamstercoin :) Hamster Community",
         "@_hamster_coin #Hamstercoin if you want to be millionaire, buy more hamstercoin :):) Hamster Community",
         "@_hamster_coin #Hamstercoin uture is hamstercoin :) Hamster Community",
         "@_hamster_coin #Hamstercoin love is hamster :) Hamster Community",
         "@_hamster_coin #Hamstercoin total burning is %49 :):) Hamster Community",
         "@_hamster_coin #Hamstercoin dont forget to take your place in the most popular project of the world hamster swap :):) Hamster Community",
         "@_hamster_coin #Hamstercoin winner is always hamstercoin :) Hamster Community",
         "@_hamster_coin #Hamstercoin elon loves the hamster :) Hamster Community",
         "@_hamster_coin #Hamstercoin our road is long!! HODL :) Hamster Community",
         "@_hamster_coin #Hamstercoin of course hamstercoin:):) Hamster Community",
         "@_hamster_coin #Hamstercoin  buy more hamstercoin :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin life is better with hamstercoin:):):)  Hamster Community",
         "@_hamster_coin #Hamstercoin  we are with you forever :):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin NFT is coming :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin metaverse is coming!! :):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamster has mad skillz :):):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin elon musk said that hamster has mad skillz:):):) Hamster Community",
         "@_hamster_coin #Hamstercoin good days are coming :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin rep sherman says the biggest threat to ethereum is dogecoin then jack dorsey said hamstercoin is stronger than dogecoin:):) Hamster Community",
         "@_hamster_coin #Hamstercoin soon NFT:):):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin swap is the best :):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin dont miss the hamstercoin:):):):)  Hamster Community",
         "@_hamster_coin #Hamstercoin the journey begins :):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin catch the train :):):):):):):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin ham will be listed on dex trade  :):):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin chose the hamstercoin to gain $btc :):):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin it is time to hamstercoin :):):):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin go to the moon :):):):):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin we are hamsters armies:):):):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin Are you ready for hamstercoin :):):):):):):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin forever :):):):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin be happy with hamstercoin :):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin metahamster!! that sounds good :):):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin all in :):):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin buy the dip :):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin you are the best :):):):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin you are the best project ever:):):):)  Hamster Community",
         "@_hamster_coin #Hamstercoin buy now or cry later :):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamwallet is coming :):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin great project :):):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin is number one:):):):):):):)  Hamster Community",
         "@_hamster_coin #Hamstercoin the best coin was hamstercoin in 2021 :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamster is new shiba :) Hamster Community",
         "@_hamster_coin #Hamstercoin ticktack ticktack:) Hamster Community",
         "@_hamster_coin #Hamstercoin join our community :) Hamster Community",
         "@_hamster_coin #Hamstercoin best team!!:):):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamsterpower is amazing:):)  Hamster Community",
         "@_hamster_coin #Hamstercoin  my baby is hamster :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin my fav coin is hamster :) Hamster Community",
         "@_hamster_coin #Hamstercoin king of coin is hamstercoin:):)  Hamster Community",
         "@_hamster_coin #Hamstercoin we are hamsters:):) Hamster Community",
         "@_hamster_coin #Hamstercoin certik certificate approved:):):) Hamster Community",
         "@_hamster_coin #Hamstercoin will fly soon :) Hamster Community",
         "@_hamster_coin #Hamstercoin catch it :):) Hamster Community Hamster Community",
         "@_hamster_coin #Hamstercoin the hamsterfamily is very lovely :):) Hamster Community",
         "@_hamster_coin #Hamstercoin we love jack dorsey:):):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin 100x soon:):):) Hamster Community",
         "@_hamster_coin #Hamstercoin my fav crypto is hamstercoin:):):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin family is growing day by day:) Hamster Community",
         "@_hamster_coin #Hamstercoin Let's do this! Hamsterswaaaaap:) Hamster Community",
         "@_hamster_coin #Hamstercoin Hamsterswap is coming :) Hamster Community",
         "@_hamster_coin #Hamstercoin Hamster ecosystem start with Hamsterswap:):) Hamster Community",
         "@_hamster_coin #Hamstercoin new era with Hamster swap:) Hamster Community",
         "@_hamster_coin #Hamstercoin Time to stake time to Hamster swap:) Hamster Community",
         "@_hamster_coin #Hamstercoin this is Hamster swap :):):) Hamster Community",
         "@_hamster_coin #Hamstercoin come to Hamster Swap:):) Hamster Community",
         "@_hamster_coin #Hamstercoin to swap or not to swap Hamster swap:)  Hamster Community",
         "@_hamster_coin #Hamstercoin I admire the team:):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin  we trust the team:):) Hamster Community",
         "@_hamster_coin #Hamstercoin i believe hamstercoin:):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamster has mad skillz, you know that? :):) Hamster Community",
         "@_hamster_coin  #Hamstercoin  we are with you:):):) Hamster Community",
         "@_hamster_coin #Hamstercoin 2022 will be amazing for hamstercoin:):):) Hamster Community",
         "@_hamster_coin #Hamstercoin do to it:) Hamster Community",
         "@_hamster_coin #Hamstercoin dont stop:) Hamster Community",
         "@_hamster_coin #Hamstercoin you are very strong:) Hamster Community",
         "@_hamster_coin #Hamstercoin np we trust the team:) Hamster Community",
         "@_hamster_coin #Hamstercoin everything will be good:):) Hamster Community",
         "@_hamster_coin #Hamstercoin i'll wait it :):) Hamster Community",
         "@_hamster_coin #Hamstercoin new ath is coming:):) Hamster Community",
         "@_hamster_coin #Hamstercoin i love the team! ALWAYS i will:):):) Hamster Community",
         "@_hamster_coin #Hamstercoin dont miss the coin super:):) Hamster Community",
         "@_hamster_coin #Hamstercoin join our army:) Hamster Community",
         "@_hamster_coin #Hamstercoin  lets do this:):):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin  i wait jack dorsey:):):) Hamster Community",
         "@_hamster_coin #Hamstercoin  i believe this project:):) Hamster Community",
         "@_hamster_coin #Hamstercoin buy back and burn  will start!!!:) Hamster Community",
         "@_hamster_coin #Hamstercoin it’s worth the wait:):) Hamster Community",
         "@_hamster_coin #Hamstercoin  community is the best thing.:):) Hamster Community",
         "@_hamster_coin #Hamstercoin  hamster armies are here!!:):) Hamster Community",
         "@_hamster_coin #Hamstercoin  just trust the team:):) Hamster Community",
         "@_hamster_coin #Hamstercoin  the best team that i see:):) Hamster Community",
         "@_hamster_coin #Hamstercoin  you’ll become a hamstercoin millionaire in 2022:):):):) Hamster Community",
         "@_hamster_coin #Hamstercoin  it is amazing:):) Hamster Community",
         "@_hamster_coin #Hamstercoin unbelievable team:) Hamster Community",
         "@_hamster_coin #Hamstercoin i love the team and hamstercoin:):) Hamster Community",
         "@_hamster_coin #Hamstercoin hamstercoin is very strong coin :) Hamster Community",
      ],
      turk_data: [
         "@_hamster_coin #hamstercoin hamster şimdiye kadarki en iyi madeni para",
         "@_hamster_coin #hamstercoin her zaman hamstercoin'in yanındayız",
         "@_hamster_coin #hamstercoin hamster takası harika",
         "@_hamster_coin #hamstercoin daha fazla kazanmak için hamstercoin'i seç",
         "@_hamster_coin #hamstercoin hamstercoin ile güçlüyüz",
         "@_hamster_coin #hamstercoin hamstercoin büyük bir büyük bsc ağında listede",
         "@_hamster_coin #hamstercoin hamstercoin ile çok mutluyuz",
         "@_hamster_coin #hamstercoin hamstercoin'e çok güveniyorum",
         "@_hamster_coin #hamstercoin hamstercoin yakında uzayda",
         "@_hamster_coin #hamstercoin hamstercoin için çok heyecanlıyım",
         "@_hamster_coin #hamstercoin jack dorsey hamstercoin'i destekliyor",
         "@_hamster_coin #hamstercoin hamstercoin topluluğu en iyisidir",
         "@_hamster_coin #hamstercoin sabırsızlıkla bekleyeceğim",
         "@_hamster_coin #hamstercoin 2022 hamstercoin yılı olacak",
         "@_hamster_coin #hamstercoin 2022'de hamstercoin'i kaçırmayacaksınız",
         "@_hamster_coin #hamstercoin sonunda takas!! hamstercoini seviyoruz",
         "@_hamster_coin #hamstercoin hamster yol haritası harika",
         "@_hamster_coin #hamstercoin sertifikası ve denetim sertifikası onaylandı!",
         "@_hamster_coin #hamstercoin hamstercoin'in parlak bir geleceği var",
         "@_hamster_coin #hamstercoin çok geniş ve güçlü bir topluluğa sahip",
         "@_hamster_coin #hamstercoin aşk, hamstercoin olan her şeydir",
         "@_hamster_coin #hamstercoin Milyoner olmak istiyorsan daha fazla hamstercoin al",
         "@_hamster_coin #hamstercoin toplam yakma oranı %49",
         "@_hamster_coin #hamstercoin dünyanın en popüler projesinde yerinizi almayı unutmayın",
         "@_hamster_coin #hamstercoin kripto kazananı her zaman hamstercoindir",
         "@_hamster_coin #hamstercoin yolumuz uzun!! HODL kalalım",
         "@_hamster_coin #hamstercoin sonsuza kadar yanınızdayız",
         "@_hamster_coin #hamstercoin hamster çılgın bir beceriye sahip",
         "@_hamster_coin #hamstercoin elon musk, hamsterin çılgın bir beceriye sahip olduğunu söyledi",
         "@_hamster_coin #hamstercoin güzel günler geliyor",
         "@_hamster_coin #hamstercoin jambonu dex ticaretinde listelenecek",
         "@_hamster_coin #hamstercoin $btc kazanmak için hamstercoin'i seç",
         "@_hamster_coin #hamstercoin biz hamster ordularıyız",
         "@_hamster_coin #hamstercoin hamstercoin ile mutlu ol",
         "@_hamster_coin #hamstercoin metahamster!! Kulağa hoş geliyor",
         "@_hamster_coin #hamstercoin sen gelmiş geçmiş en iyi projesin",
         "@_hamster_coin #hamstercoin hamstercoin bir numara",
         "@_hamster_coin #hamstercoin 2021'de en iyi madeni para hamstercoin'di",
         "@_hamster_coin #hamstercoin hamstercoin ailesi her geçen gün büyüyor",
         "@_hamster_coin #hamstercoin Hamster ekosistemi Hamsterswap ile başlar",
         "@_hamster_coin #hamstercoin Hamster takasıyla yeni dönem başlıyor",
         "@_hamster_coin #hamstercoin Hamster takasına zaman ayırma zamanı",
      ],
   }),
   methods: {
      refresh() {
         location.reload();
      },
   },
   mounted() {
      window.twttr = (function (d, s, id) {
         let js,
            fjs = d.getElementsByTagName(s)[0],
            t = window.twttr || {};
         if (d.getElementById(id)) return t;
         js = d.createElement(s);
         js.id = id;
         js.src = "https://platform.twitter.com/widgets.js";
         fjs.parentNode.insertBefore(js, fjs);

         t._e = [];
         t.ready = function (f) {
            t._e.push(f);
         };
         return t;
      })(document, "script", "twitter-wjs");

      const lang_name = document.cookie;
      this.lang_type = lang_name;
      if (lang_name === "usa") {
         const data = this.usa_data;
         this.random_text = data[Math.floor(Math.random() * data.length)];
      } else {
         const data = this.turk_data;
         this.random_text = data[Math.floor(Math.random() * data.length)];
      }

      const text = this.random_text;
      const res = text.replace("@", "%23").replace("#", "%40");
      // console.log(text, res);
   },
};
</script>

<style lang="scss" scoped>
.tweets-list {
   column-count: 3;
   column-gap: 15px;
   @media (max-width: 1200px) {
      column-count: 2;
   }
   @media (max-width: 768px) {
      column-count: 2;
   }
   @media (max-width: 414px) {
      column-count: 1;
   }
}

.block {
   margin: 0;
   display: grid;
   grid-template-rows: 1fr auto;
   break-inside: avoid;
}

.row {
   @media (max-width: 768px) {
      margin-left: 0 !important;
   }
}

.generator {
   @media (max-width: 760px) {
      flex-wrap: wrap-reverse;
   }
   display: flex;
   justify-content: center;
   align-items: center;
   min-height: 55vh;

   &__body {
      width: 900px;
      background-color: #1e1e1e;
      border-radius: 15px;
   }

   &__header {
      background: #8a826e;
      text-align: center;
      padding: 15px;
      background: linear-gradient(267.85deg, #ed835a 3.33%, #f3b425 89.15%);
      font-weight: 500;
      border-radius: 10px 10px 0 0;
      font-size: 14px;
   }

   &__text {
      border: 2px dashed #444;
      margin: 20px 15px;
      padding: 20px;
      font-weight: 500;
      font-size: 21px;
   }

   &__bg {
      @media (max-width: 760px) {
         margin-top: -180px;
      }
      @media (max-width: 414px) {
         display: none;
      }
      width: 300px;
      margin-right: 20px;
   }
}

.v-btn.refresh {
   background: linear-gradient(267.85deg, #ed835a 3.33%, #f3b425 89.15%);
}
</style>
